# Generated by Django 3.1.2 on 2020-11-04 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254)),
                ('name', models.CharField(default='-', max_length=100)),
                ('trade_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('trade_side', models.CharField(default='none', max_length=100)),
                ('trade_quantity', models.IntegerField(default=0)),
                ('trade_price', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'employee1',
            },
        ),
    ]
