# Generated by Django 3.1.2 on 2020-11-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20201104_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
