# Generated by Django 3.1.2 on 2020-11-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20201104_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_price',
            field=models.IntegerField(default=0),
        ),
    ]
