# Generated by Django 3.1 on 2020-11-09 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_auto_20201109_1114'),
        ('trade', '0005_trade_trade_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trade',
            name='contract_id',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='contract.contract'),
        ),
        migrations.AddField(
            model_name='trade',
            name='contract_name',
            field=models.CharField(default='contract1', max_length=100),
        ),
        migrations.AddField(
            model_name='trade',
            name='contract_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trade',
            name='net_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trade',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='trade',
            table=None,
        ),
    ]
