# Generated by Django 3.1.2 on 2020-11-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(default='-', max_length=100)),
                ('contract_type', models.CharField(default='-', max_length=100)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
