# Generated by Django 3.1.2 on 2020-11-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_size',
            field=models.IntegerField(default=0),
        ),
    ]
