# Generated by Django 3.1.2 on 2020-11-04 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20201104_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contract',
            name='frequency',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
