# Generated by Django 3.1 on 2020-11-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_auto_20201104_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_priceType',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='contract',
            table=None,
        ),
    ]
